export type LanguageTag =
    "language_eng" |
    "language_kor" |
    "language_rus" |
    "language_spa" |
    "language_por" |
    "language_zho" |
    "language_deu" |
    "language_jpn" |
    "language_fra" |
    "language_swe" |
    "language_nld" |
    "language_pol" |
    "language_dan" |
    "language_nor" |
    "language_ita" |
    "language_tha" |
    "language_fin" |
    "language_hun" |
    "language_ces" |
    "language_tur" |
    "language_ara" |
    "language_ron" |
    "language_vie" |
    "language_ase" |
    "language_bfi" |
    "language_dse" |
    "language_fsl" |
    "language_kvk" ;
